# Generated by Django 2.1.3 on 2018-12-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("summer_project", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventsInfo",
        ),
    ]
