# Generated by Django 2.0.6 on 2018-07-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
