# Generated by Django 2.1b1 on 2018-07-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='pic',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
