# Generated by Django 2.0.6 on 2018-07-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_project', '0002_mycustomuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycustomuser',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='mycustomuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
