# Generated by Django 2.0.6 on 2018-07-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_project', '0003_auto_20180728_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='contact',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
