# Generated by Django 2.0.6 on 2018-07-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_project', '0004_auto_20180729_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='father_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
