# Generated by Django 2.0.6 on 2018-07-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calEvents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="date",
            field=models.DateField(),
        ),
    ]
