# Generated by Django 2.1.2 on 2018-12-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calEvents", "0002_auto_20180721_2219"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
