# Generated by Django 2.0.6 on 2018-06-23 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message="First Name shouldn't contains Numbers, Special Characters etc.", regex='^[a-zA-Z.+-]*$')]),
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message="Last Name shouldn't contains Numbers, Special Characters etc.", regex='^[a-zA-Z.+-]*$')]),
        ),
    ]
